### PR TITLE
Update extensions.yml

### PR DESCRIPTION
**Pull request by TheGreatWizard**
Data Quality extension added

### CODE REVIEW

**Comment by balazsdukai** [comment]
The linked pdf doesn't work for me, only if view it by navigating to the file from the github repo, but not if click on the link directly as it is in the `extensions.yml`. Maybe better to add the link to the repo @hugoledoux ? https://github.com/TheGreatWizard/data-quality

**Comment by hugoledoux** [comment]
serious? it works for me with firefox and chrome... what you get, 404?

It's surely the spaces in the filename, @TheGreatWizard can you fix those and make a new PR perhaps?

**Comment by balazsdukai** [comment]
I'm trying on firefox too and it tells me that it's an 'Invalid or corrupted PDF structure'.

PDF.js v2.4.457 (build: 384c00ab6)
Message: Invalid PDF structure.

If I download the file and try to view it in a different pdf viewer than i get an error that its an html file not pdf.

I think it's more related to how github serves the content instead of the spaces.

**Comment by TheGreatWizard** [comment]
It works for me with firefox, chrome and edge.
I've changed the PDF file name anyway and made new PR.

**Pull request merged**
